### ISSUE TITLE
补充readme

### ISSUE THREAD

**Issue by WenmuZhou** [adreamerof/PixelCNN#2]
选手你好，

repo里系列地方需要补充或修改一下
1. readme里补充eval命令，并且模型和指标放在readme
2. 给的数据集下载地址不是cifar10，这个确认一下
PaddlePaddle-RD

**Comment by adreamerof** [comment]
你好，已更新该repo，请重新验收。

**Comment by adreamerof** [comment]
> 
> 
> 选手你好，
> 
> repo里系列地方需要补充或修改一下
> 
>     1. readme里补充eval命令，并且模型和指标放在readme
> 
>     2. 给的数据集下载地址不是cifar10，这个确认一下
>        PaddlePaddle-RD

你好，已更新该repo，请重新验收。

**Comment by WenmuZhou** [comment]
好的
