### ISSUE TITLE
训练时，loss 反向传播报错

### ISSUE THREAD

**Issue by WenmuZhou** [adreamerof/PixelCNN#3]
我启动训练报了下面的错误
paddle版本：2.2
命令 CUDA_VISIBLE_DEVICES=7 python3 main.py -r ''
![image](https://user-images.githubusercontent.com/12406017/139828703-137d1d41-3dbf-4407-99ee-cf97a141e315.png)

**Comment by adreamerof** [comment]
> 
> 
> 我启动训练报了下面的错误 paddle版本：2.2 命令 CUDA_VISIBLE_DEVICES=7 python3 main.py -r '' ![image](https://user-images.githubusercontent.com/12406017/139828703-137d1d41-3dbf-4407-99ee-cf97a141e315.png)

![图片](https://user-images.githubusercontent.com/49576421/139832060-ad8a196c-da10-426a-9afb-ec865fad1d66.png)
老师我们这边运行没有问题。

**Comment by WenmuZhou** [comment]
你的环境是啥，我看看我这边要不要调整啥

**Comment by adreamerof** [comment]
> 
> 
> 你的环境是啥，我看看我这边要不要调整啥

paddle 2.1.2
python 3.7.4

**Comment by WenmuZhou** [comment]
![image](https://user-images.githubusercontent.com/12406017/139833185-9ebb7564-228c-4417-a1a6-4055fd230614.png)
这里不是写的2.2的paddle吗

**Comment by adreamerof** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/12406017/139833185-9ebb7564-228c-4417-a1a6-4055fd230614.png) 这里不是写的2.2的paddle吗

不好意思老师，这是之前写的readme，忘改了。我修改一下，麻烦您重新试试。

**Comment by WenmuZhou** [comment]
我训练第一个batch，网络输出就为0了
![image](https://user-images.githubusercontent.com/12406017/139854927-e3430004-53e3-4fb1-84b3-005888a692f0.png)

**Comment by adreamerof** [comment]
> 
> 
> 我训练第二个batch，网络输出就为0了，第一个iter之后loss特别大，需要确认一下git和aistudio是否一致
> 
> ![image](https://user-images.githubusercontent.com/12406017/139858744-c3d46ffc-15b9-4742-84e8-8eb778f01e18.png)
> 
> ![image](https://user-images.githubusercontent.com/12406017/139854927-e3430004-53e3-4fb1-84b3-005888a692f0.png)

您好，这个问题也困扰了我们很久，我们反复确认模型的前向、反向和loss等各方面都没有问题，后来以为是weight_norm层的问题，跟老师讨论了很久也未解决，最后发现应该是paddle默认初始化参数的问题，用pytorch随机初始化的参数转为.pdparams以后load进paddle中就能正常训练，跟相关负责老师反馈过这个问题了，这是随机初始化的参数链接：https://pan.baidu.com/s/1244wsyFoChUQRuy3YP3Gzg，提取码：bqj8

**Comment by WenmuZhou** [comment]
这种情况可以将torch的初始化，在paddle里实现以下，可以参考这个https://github.com/PaddlePaddle/PaddleGAN/blob/develop/ppgan/modules/init.py#L284，我先用你提供的初始化进行验收

**Comment by WenmuZhou** [comment]
训练一段时间之后 出现了nan，需要排查是否反向没对齐
![image](https://user-images.githubusercontent.com/12406017/140029022-aba3f3aa-d1ed-4d7d-8cd9-e3e7ca03963b.png)
