### ISSUE TITLE
训练一定程度后遇到nan

### ISSUE THREAD

**Issue by WenmuZhou** [adreamerof/PixelCNN#5]
你好，我是飞桨负责验收的，在验收这篇算法时，训练一定程度之后遇到了nan的问题，看报错信息是输入的问题，建议检察一下

paddlepaddle：2.1.2

![image](https://user-images.githubusercontent.com/12406017/147021616-a6ac62d0-7f3f-4e26-b3f1-d8f4a2c16060.png)

**Comment by JingfeiHuang** [comment]
> 你好，我是飞桨负责验收的，在验收这篇算法时，训练一定程度之后遇到了nan的问题，看报错信息是输入的问题，建议检察一下
> 
> paddlepaddle：2.1.2
> 
> ![image](https://user-images.githubusercontent.com/12406017/147021616-a6ac62d0-7f3f-4e26-b3f1-d8f4a2c16060.png)

您好，我修改了部分代码，在paddlepaddle2.2.1的环境下重新运行了一下，达到了验收指标，没有遇到NAN的情况，相关代码、预训练模型（[paddle pretrained model](https://pan.baidu.com/s/1uXkU2pvffUsLUNd-pqkacA) ，提取码：sxkq）及训练过程日志（[paddle_train.log](https://github.com/adreamerof/PixelCNN/blob/master/paddle_train.log)）已更新，增加了一个test.py文件用于测试，您可以运行test.py加载预训练模型进行测试，也可以运行main.py重新训练，谢谢！
